ARG BASE=node:20.18.0
FROM ${BASE} AS base

WORKDIR /app

# Install dependencies (this step is cached as long as the dependencies don't change)
COPY package.json pnpm-lock.yaml ./

# Update npm and install essential tools
RUN npm install -g npm@latest && \
    npm install -g corepack@latest && \
    corepack enable pnpm && \
    corepack use pnpm@latest-10 && \
    npm install -g wrangler@latest

# Copy the entire project
COPY . .

# Torna o script postdeploy.sh executável
RUN chmod +x postdeploy.sh

# Fix bindings.sh file format
RUN tr -d '\r' < bindings.sh > bindings.tmp && \
    mv bindings.tmp bindings.sh && \
    chmod +x bindings.sh

# Build application
RUN pnpm run build

# Expose application port
EXPOSE 5173

# Start application
CMD ["pnpm", "run", "dockerstart"]
