#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

vars = {
  SESSION_SECRET = "yyLHd/wlFnHeBWSyP9u+bVgltnDjzfN31TAT2z5svy4="
  # Outras variáveis...
}
